import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-blue-600 text-white p-3 flex items-center justify-center gap-4 sticky top-0 z-50">
          <span className="font-semibold">
            대시보드 전역 공지: Nexus 시스템 정기점검 완료
          </span>
          <input
            type="text"
            placeholder="상태가 유지되는지 확인하세요"
            className="text-black px-3 py-1 rounded w-64 outline-none"
          />
        </div>
        {children}
      </body>
    </html>
  );
}
